### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by gondzo** [cisco-open-source/qtwebdriver#24]
When linking the library, there are some mongoose issues like
`WebDriver_core.lib(mongoose.obj):-1: error: LNK2019: unresolved external symbol ___WSAFDIsSet@8 referenced in function _master_thread`
or (when built with 'WD_BUILD_MONGOOSE': 0)
`WebDriver_core.lib(webdriver_server.obj):-1: error: LNK2019: unresolved external symbol _mg_start referenced in function "public: int __thiscall webdriver::Server::Start(void)" (?Start@Server@webdriver@@QAEHXZ)`

The project links to 
`LIBS+=-L"C:/qtwebdriver/out/Default/"    -lWebDriver_core \
                                        -lchromium_base \
                                        -lWebDriver_extension_qt_base \
                                        -lWebDriver_extension_qt_web \
                                        -lWebDriver_extension_qt_quick \
                                        -lWebDriver_extension_qt_quick_web \
                                        -ltest_widgets
`
Compiler MSVC2012, qt5 with webkit
Any ideas on the cause ?

**Comment by hekra01** [comment]
Yes, WD, requires mongoose.
If you set `'WD_BUILD_MONGOOSE': '0'`, then you need to:
* define the include for mongoose by defining 'MONGOOSE_INC_PATH` which defaults to `'MONGOOSE_INC_PATH': 'src/third_party/mongoose' .
* provide your own mongoose libs

I suggest to set `'WD_BUILD_MONGOOSE':1`.
If you set it to 0 because you fear potential licensing issues, please note that WD uses mongoose v 3.1, for which the license is still MIT. So no issues linking statically with it.

**Comment by hekra01** [comment]
Should be fixed. Let me know if other issues
